language: python
python:
  - "2.7"
  - "3.3"
install:
  # Install seam to test
  - "pip install -e ."
script:
  - "python runtests.py -v --strict"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r dev-requirements.txt && make docs; fi